[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
ed-journals = { path = "../ed-journals", features = ["strict", "blocking", "async"] }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
